version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    ports:
      - 8000:2015
    environment:
      NETTE_DEBUG: 1
    volumes:
      - ./:/srv/app:delegated

  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: componette
    volumes:
      - ./.docker/data/db:/var/lib/mysql

  adminer:
    image: dockette/adminer:dg
    ports:
      - 8888:80